#!/bin/sh

set -eu

# Deliberately word-splitting:
# shellcheck disable=SC2046
set -- $(
    gnome-desktop-testing-runner -l gdk-pixbuf/ |
    cut -f1 -d' ' |
    grep -v '^gdk-pixbuf/pixbuf-randomly-modified\.test$'
)

exec gnome-desktop-testing-runner \
--report-directory="$AUTOPKGTEST_ARTIFACTS" \
--tap \
-- \
"$@"
